name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # Build Account Service
      - name: Build Account Service
        run: |
          cd account-service
          mvn clean package -DskipTests

      # Build API Gateway
      - name: Build API Gateway
        run: |
          cd api-gateway
          mvn clean package -DskipTests

      # Build Eureka Server
      - name: Build Eureka Server
        run: |
          cd eureka-server
          mvn clean package -DskipTests

      
    

      - name: Build Docker images API-GATEWAY
        run: |
         docker build -t ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest -f api-gateway/Dockerfile api-gateway
      - name: Build Docker image ACCOUNT-SERVICE
        run: |  
         docker build -t ${{ secrets.DOCKER_USERNAME }}/account-service:latest -f account-service/Dockerfile account-service
      - name: Build Docker image TRANSACTION-SERVICE
        run: | 
         docker build -t ${{ secrets.DOCKER_USERNAME }}/eureka-server:latest -f eureka-server/Dockerfile eureka-server

      - name: Push Docker images
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/account-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/eureka-server:latest

