name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Build Account Service
      - name: Build Account Service
        run: |
          cd account-service
          mvn clean package -DskipTests

      # Build API Gateway
      - name: Build API Gateway
        run: |
          cd api-gateway
          mvn clean package -DskipTests

      # Build Eureka Server
      - name: Build Eureka Server
        run: |
          cd eureka-server
          mvn clean package -DskipTests